use super::{MMIO, Raw as RawReg};

pub const DDR_CTRL: MMIO<RawReg> = unsafe { MMIO::base(DDR_CTRL_BASE) };
pub const DDR_CTRL_SECURE_ALIAS: MMIO<RawReg> = unsafe { MMIO::base(DDR_CTRL_SECURE_ALIAS_BASE) };
pub const DDR_CTRL_CHANNEL: MMIO<RawReg> = unsafe { MMIO::base(DDR_CTRL_CHANNEL_BASE) };
pub const DDR_CTRL_PHY_CONTROL: MMIO<RawReg> = unsafe { MMIO::base(DDR_CTRL_PHY_CONTROL_BASE) };

pub const DDR_PHY: MMIO<RawReg> = unsafe { MMIO::base(DDR_PHY_BASE) };
pub const DDR_PHY_SUB_A: MMIO<RawReg> = unsafe { MMIO::base(DDR_PHY_SUB_A_BASE) };
pub const DDR_PHY_SUB_B: MMIO<RawReg> = unsafe { MMIO::base(DDR_PHY_SUB_B_BASE) };
pub const DDR_PHY_OTHER_CONTROL: MMIO<RawReg> = unsafe { MMIO::base(DDR_PHY_OTHER_CONTROL_BASE) };

pub const DDR_PHY_FREQ_POINT_STEP: u32 = 0x4000;

pub const DDR_CTRL_BASE: u32 = 0xC000_0000;
const DDR_CTRL_SECURE_ALIAS_BASE: u32 = 0xF000_0000;
pub const DDR_CTRL_CHANNEL_OFFSET: u32 = 0x200;
pub const DDR_CTRL_CHANNEL_BASE: u32 = DDR_CTRL_BASE + DDR_CTRL_CHANNEL_OFFSET;
const DDR_CTRL_PHY_CONTROL_OFFSET: u32 = 0x1000;
const DDR_CTRL_PHY_CONTROL_BASE: u32 = DDR_CTRL_BASE + DDR_CTRL_PHY_CONTROL_OFFSET;

const DDR_PHY_BASE: u32 = 0xC004_0000;
const DDR_PHY_SUB_A_OFFSET: u32 = 0x3000;
const DDR_PHY_SUB_A_BASE: u32 = DDR_PHY_BASE + DDR_PHY_SUB_A_OFFSET;
const DDR_PHY_SUB_B_OFFSET: u32 = DDR_PHY_SUB_A_OFFSET + 0x200;
const DDR_PHY_SUB_B_BASE: u32 = DDR_PHY_BASE + DDR_PHY_SUB_B_OFFSET;
const DDR_PHY_OTHER_CONTROL_OFFSET: u32 = 0x1_0000;
const DDR_PHY_OTHER_CONTROL_BASE: u32 = DDR_PHY_BASE + DDR_PHY_OTHER_CONTROL_OFFSET;
